[postgres2@pg101 ~]$ cat ~/wzo28/postgresql.conf
listen_addresses = '*'
port = 9867
unix_socket_directories = '/tmp'

shared_buffers = 384MB
work_mem = 6MB
temp_buffers = 20MB
effective_cache_size = 1536MB
max_connections = 25

fsync = on
checkpoint_timeout = 35min
commit_delay = 500
wal_buffers = 64MB

log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_min_messages = info


# ssd приколы
random_page_cost = 1.1
effective_io_concurrency = 200